XCOPY "..\Client\bin\Debug\net6.0\Oqtane.ChatHubs.Client.Oqtane.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Client\bin\Debug\net6.0\Oqtane.ChatHubs.Client.Oqtane.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Server\bin\Debug\net6.0\Oqtane.ChatHubs.Server.Oqtane.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Server\bin\Debug\net6.0\Oqtane.ChatHubs.Server.Oqtane.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Shared\bin\Debug\net6.0\Oqtane.ChatHubs.Shared.Oqtane.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Shared\bin\Debug\net6.0\Oqtane.ChatHubs.Shared.Oqtane.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorAlerts\bin\Debug\net6.0\BlazorAlerts.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorAlerts\bin\Debug\net6.0\BlazorAlerts.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Accordion\bin\Debug\net6.0\Hwavmvid.Accordion.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Accordion\bin\Debug\net6.0\Hwavmvid.Accordion.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorSelect\bin\Debug\net6.0\BlazorSelect.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorSelect\bin\Debug\net6.0\BlazorSelect.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorModal\bin\Debug\net6.0\BlazorModal.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorModal\bin\Debug\net6.0\BlazorModal.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorWindows\bin\Debug\net6.0\BlazorWindows.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorWindows\bin\Debug\net6.0\BlazorWindows.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorTabs\bin\Debug\net6.0\BlazorTabs.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorTabs\bin\Debug\net6.0\BlazorTabs.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Pager\bin\Debug\net6.0\Hwavmvid.Pager.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Pager\bin\Debug\net6.0\Hwavmvid.Pager.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDraggableList\bin\Debug\net6.0\BlazorDraggableList.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDraggableList\bin\Debug\net6.0\BlazorDraggableList.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.FileUpload\bin\Debug\net6.0\Hwavmvid.FileUpload.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.FileUpload\bin\Debug\net6.0\Hwavmvid.FileUpload.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.ColorPicker\bin\Debug\net6.0\Hwavmvid.ColorPicker.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.ColorPicker\bin\Debug\net6.0\Hwavmvid.ColorPicker.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Video\bin\Debug\net6.0\Hwavmvid.Video.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Video\bin\Debug\net6.0\Hwavmvid.Video.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.VideoPlayer\bin\Debug\net6.0\Hwavmvid.VideoPlayer.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.VideoPlayer\bin\Debug\net6.0\Hwavmvid.VideoPlayer.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorBrowserResize\bin\Debug\net6.0\BlazorBrowserResize.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorBrowserResize\bin\Debug\net6.0\BlazorBrowserResize.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDropdown\bin\Debug\net6.0\BlazorDropdown.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDropdown\bin\Debug\net6.0\BlazorDropdown.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorNotifications\bin\Debug\net6.0\BlazorNotifications.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorNotifications\bin\Debug\net6.0\BlazorNotifications.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDynamicLayout\bin\Debug\net6.0\BlazorDynamicLayout.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDynamicLayout\bin\Debug\net6.0\BlazorDynamicLayout.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorSlider\bin\Debug\net6.0\BlazorSlider.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorSlider\bin\Debug\net6.0\BlazorSlider.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDevices\bin\Debug\net6.0\BlazorDevices.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDevices\bin\Debug\net6.0\BlazorDevices.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDownload\bin\Debug\net6.0\BlazorDownload.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\BlazorDownload\bin\Debug\net6.0\BlazorDownload.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Motiondetection\bin\Debug\net6.0\Hwavmvid.Motiondetection.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Motiondetection\bin\Debug\net6.0\Hwavmvid.Motiondetection.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Stringpics\bin\Debug\net6.0\Hwavmvid.Stringpics.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Stringpics\bin\Debug\net6.0\Hwavmvid.Stringpics.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Jsapinotifications\bin\Debug\net6.0\Hwavmvid.Jsapinotifications.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Jsapinotifications\bin\Debug\net6.0\Hwavmvid.Jsapinotifications.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Jsapigeolocation\bin\Debug\net6.0\Hwavmvid.Jsapigeolocation.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Jsapigeolocation\bin\Debug\net6.0\Hwavmvid.Jsapigeolocation.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Blackjack\bin\Debug\net6.0\Hwavmvid.Blackjack.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Blackjack\bin\Debug\net6.0\Hwavmvid.Blackjack.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulette\bin\Debug\net6.0\Hwavmvid.Roulette.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulette\bin\Debug\net6.0\Hwavmvid.Roulette.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettesurface\bin\Debug\net6.0\Hwavmvid.Roulettesurface.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettesurface\bin\Debug\net6.0\Hwavmvid.Roulettesurface.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettebetoptions\bin\Debug\net6.0\Hwavmvid.Roulettebetoptions.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettebetoptions\bin\Debug\net6.0\Hwavmvid.Roulettebetoptions.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Rouletteitellisense\bin\Debug\net6.0\Hwavmvid.Rouletteitellisense.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Rouletteitellisense\bin\Debug\net6.0\Hwavmvid.Rouletteitellisense.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Rouletteshared\bin\Debug\net6.0\Hwavmvid.Rouletteshared.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Rouletteshared\bin\Debug\net6.0\Hwavmvid.Rouletteshared.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettecoins\bin\Debug\net6.0\Hwavmvid.Roulettecoins.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettecoins\bin\Debug\net6.0\Hwavmvid.Roulettecoins.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettebets\bin\Debug\net6.0\Hwavmvid.Roulettebets.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Roulettebets\bin\Debug\net6.0\Hwavmvid.Roulettebets.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Motorsport.Racewaymaps\bin\Debug\net6.0\Hwavmvid.Motorsport.Racewaymaps.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Motorsport.Racewaymaps\bin\Debug\net6.0\Hwavmvid.Motorsport.Racewaymaps.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Motorsport.Shared\bin\Debug\net6.0\Hwavmvid.Motorsport.Shared.dll" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y
XCOPY "..\Hwavmvid.Motorsport.Shared\bin\Debug\net6.0\Hwavmvid.Motorsport.Shared.pdb" "..\..\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\" /Y


XCOPY "..\Server\wwwroot\Modules\Oqtane.ChatHubs\*" "..\..\oqtane.framework\Oqtane.Server\wwwroot\Modules\Oqtane.ChatHubs\" /Y /S /I